### ISSUE TITLE
Linux fail

### ISSUE THREAD

**Issue by tunage** [bitcoinplusorg/xbcwalletsource#1]
src/qt/optionsmodel.cpp:149:72: error: conversion from ‘int64_t {aka long int}’ to ‘const QVariant’ is ambiguous
             return settings.value("fTorEnabled", GetArg("-torproxy", 1));

I found a way around it but its REALLY dirty.
comment out line 149 in optionsmodel.cpp
//return settings.value("fTorEnabled", GetArg("-torproxy", 1));

This will disable most of the wallet Tor connection features BUT you can still enable "native tor" (option 3 in wallet networking options) and if Tor is running at wallet start, it will connect just fine.

**Comment by Bushstar** [comment]
That is dirty. I believe that you can use the QVariant::fromValue function to convert the value from GetArg. Or you can switch to the much newer 2.7 branch but that does not have an ancient Tor client bundled with it but relies on an external Tor proxy.
