### ISSUE TITLE
Mac issue

### ISSUE THREAD

**Issue by mohitcis** [bitcoinplusorg/xbcwalletsource#4]
When I am running the build for mac it is giving following error

make: *** No rule to make target `obj/fugue.o', needed by `bitcoinplusd'.  Stop.

**Comment by Bushstar** [comment]
Please switch to and build the master-2.7 branch or go to the release tab and download the Mac build of XBC 2.7.0.

https://github.com/bitcoinplusorg/xbcwalletsource/releases
