### ISSUE TITLE
Missing dependencies in build instructions

### ISSUE THREAD

**Issue by PanderMusubi** [bitcoinplusorg/xbcwalletsource#6]
Please add to https://github.com/bitcoinplusorg/xbcwalletsource/blob/origin/doc/readme-qt.rst that for Debian (Ubuntu) `sudo apt-get install libevent-dev` is also needed. Otherwise `make` stops at

    fatal error: event2/util.h: No such file or directory

And add `sudo apt-get install libminiupnpc-dev` to prevent failure on

    fatal error: miniupnpc/miniwget.h: No such file or directory

Then, the build halts at

    Makefile:5604: recipe for target 'build/optionsmodel.o' failed
make: *** [build/optionsmodel.o] Error 1

So, please, fix teh cause of that too.

PS  Offer also releases here for latest stable versions of Debian and Ubuntu.

**Comment by Bushstar** [comment]
libevent-dev is no longer required to build the master-2.7 branch which will soon become the default branch.

**Comment by PanderMusubi** [comment]
Could you please include prebuild executablesfor each release here on GitHub? Preferably one for latest stable Debian and one for Ubuntu. For many users, building themselves is a bridge too far. Thanks.

**Comment by Bushstar** [comment]
The 2.7.0 prebuilt binaries for Windows, Mac and Linux are available from the release tab, see the link below.

https://github.com/bitcoinplusorg/xbcwalletsource/releases

**Comment by PanderMusubi** [comment]
(GitHub on mobile didn't expand the assets,  but now Indeed them. Thanks)
